### ISSUE TITLE
Please release 1.2.1 in maven repository

### ISSUE THREAD

**Issue by soid** [resthub/springmvc-router#66]
This bug was fixed a year ago, however, it has never been published: https://github.com/resthub/springmvc-router/pull/58

Could you please publish the 1.2.1 release in the maven central repository?

**Comment by bclozel** [comment]
Hi @soid 
I just released a [SNAPSHOT version](https://oss.sonatype.org/content/repositories/snapshots/org/resthub/springmvc-router/1.2.1-SNAPSHOT/) with some dependencies updates as well.
Could you try it out before I launch the release process?

**Comment by soid** [comment]
Yep, it looks alright

**Comment by bclozel** [comment]
Done! This should be available in maven central shortly.
